<?php
/**
 * Copyright © PureClarity. All rights reserved.
 * See LICENSE.txt for license details.
 */
/** @var \Pureclarity\Core\Block\Configuration $block */
/** @var \Pureclarity\Core\ViewModel\Configuration $config */

$config = $block->getPureclarityConfigurationViewModel();
if ($config->isActive()): ?>

    <div data-bind="scope: 'customerdetails'" style="display:none">
        <!-- ko if: renderTrackingEvents--><!-- /ko -->
    </div>

    <div data-bind="scope: 'cartupdate'" style="display:none">
        <!-- ko if: renderTrackingEvents--><!-- /ko -->
    </div>

    <script type="text/x-magento-init">
        { 
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "cartupdate": {
                            "component": "Pureclarity_Core/js/view/cart-update"
                        },
                        "customerdetails": {
                            "component": "Pureclarity_Core/js/view/customer-details"
                        }
                    }
                }
            }
        }
    </script>

<?php endif; ?>
