<!-- Default pureclarity search box -->
<div class="block block-search">
    <div class="block block-content">
        <div id="int_pc_search">
            <label for="pc_searchbox"><?php echo 'Search'; ?></label>
            <input id="pc_searchbox" placeholder="Search" type="text" class="input-text pc_search" />
            <button id="pc_searchbutton" type="button" class="button pc_searchbutton"><span>Search</span></button>
        </div>
    </div>
</div>