<?php
/**
 * Copyright © PureClarity. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \Pureclarity\Core\Block\Bmz $block */
?>
<div <?= $block->getBmzDataHtml() ?>
    data-pureclarity-bmz-id="<?= $block->escapeQuote($block->getBmzId()) ?>"
    class="<?= $block->escapeQuote($block->getClasses()) ?>"
    style="<?= (!$block->getDebugMode() ? 'display:none;':'') ?>">
    <?= $block->getContentHtml() ?>
</div>