<?php
/**
 * Copyright © PureClarity. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \Pureclarity\Core\Block\Configuration $block */
/** @var \Pureclarity\Core\ViewModel\Configuration $config */

$config = $block->getPureclarityConfigurationViewModel();

if ($config->isActive()): ?>
    <script type="text/javascript">
        window.pureclarityConfig = <?= /* @noEscape */ $config->getConfigurationJson() ?>;
    </script>
<?php endif; ?>