<?php echo $block->getButtonHtml() ?>

<style>
    #pc-bmz-outputContainer {margin:20px 0;min-height:50px;}
    .pc-topbuffer {margin-top:25px;}
</style>

<div id="pc-bmz-modal-popup" style="display:none;" class="admin__scope-old">
    
    <div>
        <h4>Select the Store that you would like to install the Bmz widgets on:</h4>
        <select id="pc-bmz-selectStore" class="select admin__controle-select">
            <?php foreach ($block->getStores() as $store) : ?>
                <option value="<?php echo $store['id']; ?>" ><?php echo $store['name']  ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    
    <div class="pc-topbuffer">
        <h4>Select the Theme that you would like to install the Bmz widgets on:</h4>
        <select id="pc-bmz-selectTheme" class="select admin__controle-select">
            <?php foreach ($block->getThemes() as $theme) : ?>
                <option value="<?php echo $theme['value']; ?>" ><?php echo $theme['label'];  ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <div id="pc-bmz-outputContainer">
        <div id="pc-bmz-statusMessage" style="display:none"></div>
    </div>

    <div>
        <button id="pc-runBmzInstall" onclick="pureclarityBmzObj.installBmzs()">Install BMZ Now</button>
    </div>
</div>




<script>
    var pureclarityBmzObj = pureclarityBmzObj || {};
    require(['jquery','Magento_Ui/js/modal/modal'],
        function($, modal){
            (function(window, $, modal){
                window.pureclarityBmzObj = {

                    // Set vars
                    installUrl: '<?php echo $block->getInstallUrl(); ?>',
                    modal: modal,
                    selectStore: $('#pc-bmz-selectStore'),
                    selectTheme: $('#pc-bmz-selectTheme'),
                    runButton: $('#pc-runBmzInstall'),
                    messageContainer: $('#pc-bmz-statusMessage'),
                    selectedStore: 0,
                    selectedTheme: 0,
                    isComplete: true,

                    // Initialise function
                    init: function(){
                        var options = {
                            type: 'popup',
                            responsive: true,
                            innerScroll: true,
                            title: 'PureClarity Install BMZs',
                            buttons: [{
                                text: $.mage.__('Close'),
                                class: '',
                                click: function () {
                                    this.closeModal();
                                }
                            }]
                        };
                        var popup = this.modal(options, $('#pc-bmz-modal-popup'));
                        var self = this;
                        $("#pc-bmzpopupbutton").on('click',function(){ 
                            // Ensure state is reset
                            if (self.isComplete){
                                self.resetState();
                                self.messageContainer.hide();
                            }
                            $("#pc-bmz-modal-popup").modal("openModal");
                        });
                    },

                    // Function to execute running of feed
                    installBmzs: function(){
                        if (this.isComplete){
                            this.message("Installing...");
                            this.selectedStore = this.selectStore.find(":selected").val();
                            this.selectedTheme = this.selectTheme.find(":selected").val();

                            this.selectStore.prop("disabled", true);
                            this.selectTheme.prop("disabled", true);
                            this.runButton.prop("disabled", true);

                            var urlParts = [this.installUrl + '?'];
                            urlParts.push('storeid='+this.selectedStore);
                            urlParts.push('themeid='+this.selectedTheme);
                            var self = this;
                            $.ajax({
                                url: urlParts.join('&'),
                                data: {form_key: window.FORM_KEY, storeid: this.selectedStore},
                            }).done(function(response) {
                                if (response){
                                    messageParts = ['Installation finished.</br />'];
                                    if (response.alreadyExists && response.alreadyExists.length>0) {
                                        messageParts.push('The following BMZs are ALREADY installed for the current store/theme selection: ' + response.alreadyExists.join(', '));
                                        messageParts.push(' ');
                                    }
                                    if (response.installed && response.installed.length>0){
                                        messageParts.push('The following BMZs were SUCCESSFULLY installed: ' + response.installed.join(', '));
                                        messageParts.push('<br />NOTE: You may need to clear the Magento cache before the BMZs display.');
                                    }
                                    self.message(messageParts.join('<br />'));
                                }
                                else {
                                    self.message('Error. There has been an error install BMZs. The error has been logged.');
                                }
                                self.resetState();
                            });
                        }
                    },
                    message: function(message){
                        this.messageContainer.show();
                        this.messageContainer.html("<strong>Status: </strong>" + message);
                    },
                    resetState: function(hideMessage){
                        this.isComplete = true;
                        this.selectStore.prop("disabled", false);
                        this.selectTheme.prop("disabled", false);
                        this.runButton.prop("disabled", false);
                    }
                }
            })(window, $, modal);

            // Initialise pc
            pureclarityBmzObj.init();
        }
    );
</script>



