<?php
/**
 * Copyright © PureClarity. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \Pureclarity\Core\Block\Adminhtml\Dashboard\Configured $block */
/** @var \Pureclarity\Core\ViewModel\Adminhtml\Dashboard\State $state */
$state = $block->getPureclarityStateViewModel();

/** @var \Pureclarity\Core\ViewModel\Adminhtml\Stores $stores */
$stores = $block->getPureclarityStoresViewModel();

?>
<?= $block->getChildHtml('pureclarity_dashboard_welcome_banner') ?>
<div id="pc-col1">
    <?= $block->getChildHtml('pureclarity_dashboard_content_next_steps') ?>
</div>
<div id="pc-col2">
    <?= $block->getChildHtml('pureclarity_dashboard_content_account_status') ?>
    <?= $block->getChildHtml('pureclarity_dashboard_content_stats') ?>
    <?= $block->getChildHtml('pureclarity_dashboard_content_install_zones') ?>
    <?= $block->getChildHtml('pureclarity_dashboard_content_feeds') ?>
</div>

