<?php
/**
 * Copyright © PureClarity. All rights reserved.
 * See LICENSE.txt for license details.
 */
/** @var \Pureclarity\Core\Block\Adminhtml\Dashboard\Signup $block */
/** @var \Pureclarity\Core\ViewModel\Adminhtml\Dashboard\Regions $regions */
$regions = $block->getPureclarityRegionsViewModel();
/** @var \Pureclarity\Core\ViewModel\Adminhtml\Stores $stores */
$stores = $block->getPureclarityStoresViewModel();
/** @var \Pureclarity\Core\ViewModel\Adminhtml\Dashboard\Store $store */
$store = $block->getPureclarityStoreViewModel();
?>
<div id="pc-welcome" <?php if ($stores->hasMultipleStores()): ?>class="pc-multi-store"<?php endif; ?>>
    <div id="pc-marketing-info" class="pc-box">
        <div class="pc-box-content">
            <h2><?= $block->escapeHtml(__('Welcome to PureClarity')) ?></h2>
            <p><?= $block->escapeHtml(
                __('PureClarity, an approved Magento Technology Partner, '
                    . 'is the leading AI-based eCommerce personalization platform proven to:')
            ) ?></p>
            <ul>
                <li><?= $block->escapeHtml(__('Increase online revenue by 27%')) ?></li>
                <li><?= $block->escapeHtml(__('Increase online conversion by 72%')) ?></li>
                <li><?= $block->escapeHtml(__('Increase average order value by 16%')) ?></li>
            </ul>
            <p><?= $block->escapeHtml(
                __('Features include Personalized real-time AI Recommenders, Personalized Marketing Merchandising '
                    . 'and Campaigns, Personalization within Email and Personalization within Search')
            ) ?></p>
        </div>
    </div>
    <div id="pc-sign-up" class="pc-box">
        <div class="pc-box-title-bar"><h3><?= $block->escapeHtml(__('Sign up for a free 14 day trial')) ?></h3></div>
        <div class="pc-box-content">
            <p><?= $block->escapeHtml(__('Try for Free today and increase your online revenue by 27%')) ?></p>
            <ul>
                <li><?= $block->escapeHtml(__('Access to all PureClarity features')) ?></li>
                <li><?= $block->escapeHtml(__('Access to PureClarity Academy')) ?></li>
                <li><?= $block->escapeHtml(__('Step by Step implementation guide')) ?></li>
                <li><?= $block->escapeHtml(__('Full support if needed')) ?></li>
                <li><?= $block->escapeHtml(__('No credit card required')) ?></li>
            </ul>
            <p class="pc-button">
                <button id="pc-sign-up-button" type="submit" title="Save Details"
                        class="action-default scalable primary">
                    <?= $block->escapeHtml(__('Sign up')) ?>
                </button>
            </p>
        </div>
    </div>
    <div id="pc-existing-account" class="pc-box">
        <input type="hidden" id="pc-get-store-details-url"
               value="<?= $block->escapeUrl($block->getUrl('pureclarity/dashboard/getStoreDetails')) ?>"/>
        <form id="pc-save-details-form" method="post"
              action="<?= $block->escapeUrl($block->getUrl('pureclarity/dashboard/configure')) ?>"
              data-mage-init='{"validation":{}}'>
            <div class="pc-box-title-bar"><h3><?= $block->escapeHtml(__('Already have an account?')) ?></h3></div>
            <div class="pc-box-content">
                <p><?= $block->escapeHtml(__('Enter your account details to get started')) ?></p>
                <div id="pc-account-details">
                    <p class="pc-field">
                        <label for="pc-details-access-key"><?= $block->escapeHtml(__('Access Key')) ?></label>
                        <input data-validate='{"required":true}' type="text" name="access_key"
                               id="pc-details-access-key"/>
                    </p>
                    <p class="pc-field">
                        <label for="pc-details-secret-key"><?= $block->escapeHtml(__('Secret Key')) ?></label>
                        <input data-validate='{"required":true}' type="text" name="secret_key"
                               id="pc-details-secret-key"/>
                    </p>
                    <?php if ($stores->hasMultipleStores()): ?>
                        <p class="pc-field">
                            <label class="label" for="pc-details-store-id">
                                <?= $block->escapeHtml(__('Store')) ?>
                            </label>
                            <select data-validate='{"required":true}' name="store_id" id="pc-details-store-id">
                                <?php foreach ($stores->getStoreList() as $storeId => $storeName): ?>
                                    <option value="<?= $block->escapeQuote($block->escapeHtml($storeId)) ?>"
                                        <?php if ($storeId === (int)$stores->getMagentoDefaultStore()->getId()):
                                            ?>selected="selected"<?php
                                        endif ?>>
                                        <?= $block->escapeQuote($block->escapeHtml($storeName)) ?>
                                    </option>
                                <?php endforeach ?>
                            </select>
                        </p>
                    <?php else: ?>
                        <input type="hidden" name="store_id" id="pc-details-store-id" value="0"/>
                    <?php endif; ?>
                    <p class="pc-field">
                        <label for="pc-details-region"><?= $block->escapeHtml(__('Region')) ?></label>
                        <select data-validate='{"required":true}' name="region" id="pc-details-region">
                            <?php foreach ($regions->getPureClarityRegions() as $region): ?>
                                <option value="<?= $block->escapeHtml($region['value']) ?>">
                                    <?= $block->escapeHtml($region['label']) ?>
                                </option>
                            <?php endforeach ?>
                        </select>
                    </p>
                </div>
                <div id="pc-clearfix"></div>
                <p class="pc-button">
                    <button id="pc-save-details-button" type="button"
                            title="<?= $block->escapeHtml(__('Save Details')) ?>"
                            class="action-default scalable primary">
                        <?= $block->escapeHtml(__('Save Details')) ?>
                    </button>
                </p>
            </div>
        </form>
    </div>
    <div id="pc-sign-up-form-holder">
        <div id="pc-sign-up-form-content">
            <form id="pc-sign-up-form" method="post"
                  action="<?= $block->escapeUrl($block->getUrl('pureclarity/dashboard/signup')) ?>"
                  data-mage-init='{"validation":{}}'>
                <input type="hidden" name="form_key"
                       value="<?= $block->escapeQuote($block->escapeHtml($block->getFormKey())) ?>" />
                <div class="left">
                    <h3><?= $block->escapeHtml(__('About you')) ?></h3>
                    <p class="pc-field">
                        <label class="label" for="pc-sign-up-firstname">
                            <?= $block->escapeHtml(__('First Name')) ?>
                        </label>
                        <input data-validate='{"required":true}' type="text" name="firstname"
                               id="pc-sign-up-firstname"/>
                    </p>
                    <p class="pc-field">
                        <label class="label" for="pc-sign-up-lastname">
                            <?= $block->escapeHtml(__('Last Name')) ?>
                        </label>
                        <input data-validate='{"required":true}' type="text" name="lastname" id="pc-sign-up-lastname"/>
                    </p>
                    <p class="pc-field">
                        <label class="label" for="pc-sign-up-email"><?= $block->escapeHtml(__('Email')) ?></label>
                        <input data-validate='{"required":true, "email": true}' type="text" name="email"
                               id="pc-sign-up-email"/>
                    </p>
                    <p class="pc-field">
                        <label class="label" for="pc-sign-up-company"><?= $block->escapeHtml(__('Company')) ?></label>
                        <input data-validate='{"required":true}' type="text" name="company" id="pc-sign-up-company"/>
                    </p>
                    <p class="pc-field">
                        <label class="label" for="pc-sign-up-password"><?= $block->escapeHtml(__('Password')) ?></label>
                        <input data-validate='{"required":true, "validate-admin-password":true}' type="password"
                               name="password"
                               id="pc-sign-up-password"/>
                    </p>
                </div>
                <div class="right">
                    <h3><?= $block->escapeHtml(__('About the site')) ?></h3>
                    <?php if ($stores->hasMultipleStores()): ?>
                        <p class="pc-field">
                            <label class="label" for="pc-sign-up-store-id">
                                <?= $block->escapeHtml(__('Store')) ?>
                            </label>
                            <select data-validate='{"required":true}' name="store_id" id="pc-sign-up-store-id">
                                <?php foreach ($stores->getStoreList() as $storeId => $storeName): ?>
                                    <option value="<?= $block->escapeQuote($block->escapeHtml($storeId)) ?>"
                                        <?php if ($storeId === (int)$stores->getMagentoDefaultStore()->getId()):
                                            ?>selected="selected"<?php
                                        endif ?>>
                                        <?= $block->escapeQuote($block->escapeHtml($storeName)) ?>
                                    </option>
                                <?php endforeach ?>
                            </select>
                        </p>
                    <?php else: ?>
                        <input type="hidden" name="store_id" id="pc-sign-up-store-id" value="0"/>
                    <?php endif; ?>
                    <p class="pc-field">
                        <label class="label" for="pc-sign-up-store-name">
                            <?= $block->escapeHtml(__('Store Name')) ?>
                        </label>
                        <input data-validate='{"required":true}' type="text" name="store_name"
                               id="pc-sign-up-store-name" value="" />
                    </p>
                    <p class="pc-field">
                        <label class="label" for="pc-sign-up-store-url"><?= $block->escapeHtml(__('URL')) ?></label>
                        <input data-validate='{"required":true}' type="text" name="url" id="pc-sign-up-store-url"
                               value="<?= $block->escapeQuote(
                                   $block->escapeHtml($store->getStoreURL($stores->getMagentoDefaultStore()->getId()))
                               ) ?>"/>
                    </p>
                    <p class="details">
                        <span class="label"><?= $block->escapeHtml(__('Currency')) ?></span>
                        <span class="value" id="pc-sign-up-store-currency">
                            <?= $block->escapeHtml(
                                $store->getStoreCurrency($stores->getMagentoDefaultStore()->getId())
                            ) ?>
                        </span>
                    </p>
                    <p class="details">
                        <span class="label"><?= $block->escapeHtml(__('Timezone')) ?></span>
                        <span class="value" id="pc-sign-up-store-timezone">
                            <?= $block->escapeHtml(
                                $store->getStoreTimezone($stores->getMagentoDefaultStore()->getId())
                            ) ?>
                        </span>
                    </p>
                    <p class="pc-field">
                        <label class="label" for="pc-sign-up-region"><?= $block->escapeHtml(__('Region')) ?></label>
                        <select data-validate='{"required":true}' name="region" id="pc-sign-up-region">
                            <?php foreach ($regions->getPureClarityRegions() as $region): ?>
                                <option value="<?= $block->escapeHtml($region['value']) ?>">
                                    <?= $block->escapeHtml($region['label']) ?>
                                </option>
                            <?php endforeach ?>
                        </select>
                    </p>
                </div>
            </form>
            <div id="pc-sign-up-response-holder"></div>
        </div>
    </div>
</div>