<?php
/**
 * Copyright © PureClarity. All rights reserved.
 * See LICENSE.txt for license details.
 */
/** @var \Magento\Framework\View\Element\Template $block */
?>
<div id="pc-sign-up-waiting" class="pc-box">
    <div class="pc-box-title-bar"><h3><?= $block->escapeHtml(__('Setting up account')) ?></h3></div>
    <div class="pc-box-content">
        <div class="pc-loader">
            <div class="pc-loader-outer"></div>
            <div class="pc-loader-middle"></div>
            <div class="pc-loader-inner"></div>
        </div>
        <p><?= $block->escapeHtml(__('We\'ll have you up and running')) ?></p>
        <p><?= $block->escapeHtml(__('before you can say increased revenue')) ?></p>
    </div>
</div>
<input type="hidden" id="pc-sign-up-waiting-call-url" value="<?= $block->escapeUrl($block->getUrl('pureclarity/dashboard/signupStatus')) ?>" />
