<?php
/**
 * Copyright © PureClarity. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \Pureclarity\Core\Block\Adminhtml\Dashboard $block */
/** @var \Pureclarity\Core\ViewModel\Adminhtml\Dashboard\State $state */
$state = $block->getPureclarityStateViewModel();
/** @var \Pureclarity\Core\ViewModel\Adminhtml\Stores $stores */
$stores = $block->getPureclarityStoresViewModel();

?>
<div id="pc-dashboard">
    <input type="hidden" id="pc-current-state"
           value="<?= $block->escapeQuote($block->escapeHtml($state->getStateName($stores->getStoreId()))) ?>"/>
    <input type="hidden" id="pc-current-store-id"
           value="<?= $block->escapeQuote($block->escapeHtml($stores->getStoreId())) ?>"/>
    <?php if ($state->isConfigured($stores->getStoreId()) === false): ?>
        <?= $block->getChildHtml('pureclarity_dashboard_content_signup') ?>
    <?php else: ?>
        <?= $block->getChildHtml('pureclarity_dashboard_content_configured') ?>
    <?php endif; ?>
</div>
<div id="pc-version">
    <div id="pc-logo"><span><?= $block->escapeHtml(__('PureClarity')) ?></span></div>
    <div id="pc-version-number">
        <?= $block->escapeHtml(__('Version')) ?>: <?= $block->escapeHtml($state->getPluginVersion()) ?>
    </div>
    <?php if ($state->isUpToDate()): ?>
        <div id="pc-version-status" class="pc-up-to-date">(<?= $block->escapeHtml(__('up to date')) ?>)</div>
    <?php else: ?>
        <div id="pc-version-status" class="pc-out-of-date">
            (<?= $block->escapeHtml(__('new version available - %1', $state->getNewVersion())) ?>)<br />
            <a href="https://www.pureclarity.com/docs/magento-2/#update" target="_blank">
                <?= $block->escapeHtml(__('How to update')) ?>
            </a>
        </div>
    <?php endif; ?>
</div>